/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordenarnumeros;

/**
 *
 * @author Manuel Manzano
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextFieldnumero1 = new javax.swing.JTextField();
        jTextFieldresultado = new javax.swing.JTextField();
        jTextFieldnumero2 = new javax.swing.JTextField();
        jTextFieldnumero3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Números a ordenar:");

        jButton1.setText("Ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldnumero1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldnumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumero1ActionPerformed(evt);
            }
        });

        jTextFieldresultado.setEditable(false);

        jTextFieldnumero2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldnumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumero2ActionPerformed(evt);
            }
        });

        jTextFieldnumero3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldnumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnumero3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Números ordenados:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldresultado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldnumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldnumero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumero1ActionPerformed

    private void jTextFieldnumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumero2ActionPerformed

    private void jTextFieldnumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnumero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnumero3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float num1 = 0, num2 = 0, num3 = 0;
        float lugar1 = 0, lugar2 = 0, lugar3 = 0;
        num1 = Integer.valueOf(jTextFieldnumero1.getText());
        num2 = Integer.valueOf(jTextFieldnumero2.getText());
        num3 = Integer.valueOf(jTextFieldnumero3.getText());

        if (num1 > num2 && num1 > num3) {
            if (num2 > num3) {
                lugar1 = num1;
                lugar2 = num2;
                lugar3 = num3;
            }
        } else {
            if (num2 > num3 && num2 > num1) {
                if (num1 > num3) {
                    lugar1 = num2;
                    lugar2 = num1;
                    lugar3 = num3;
                }
            }
        }
        if (num3 > num1 && num3 > num2) {
            if (num1 > num2) {
                lugar1 = num3;
                lugar2 = num1;
                lugar3 = num2;
            }
        } else {
            lugar1 = num3;
            lugar2 = num2;
            lugar3 = num1;
        }
        
        jTextFieldresultado.setText(String.valueOf(lugar1) + " > "
                + String.valueOf(lugar2) + " > " + String.valueOf(lugar3));
        
        if (num1 == num2 && num2 < num3) {
            jTextFieldresultado.setText(num1 + " es igual a " + num2
                    + "es mayor que " + num3);
        }
        if (num1 == num2 && num2 > num3) {
            jTextFieldresultado.setText(num1 + " es igual a " + num2
                    + " es memor que " + num3);
        }
        if (num1 == num3 && num3 > num2) {
            jTextFieldresultado.setText(num1 + " es igual a " + num3
                    + " es mayor que " + num2);
        }
        if (num1 == num3 && num3 < num2) {
            jTextFieldresultado.setText(num1 + " es igual a " + num3
                    + " es menor que " + num2);
        }
        if (num2 == num3 && num3 > num1) {
            jTextFieldresultado.setText(num2 + " es igual a " + num3
                    + " es menor que " + num1);
        }
        if (num2 == num3 && num3 < num1) {
            jTextFieldresultado.setText(num2 + " es igual a " + num3
                    + " es mayor que " + num1);
        }
        if (num2 == num3 && num1 == num2) {
            jTextFieldresultado.setText("Son todos iguales.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldnumero1;
    private javax.swing.JTextField jTextFieldnumero2;
    private javax.swing.JTextField jTextFieldnumero3;
    private javax.swing.JTextField jTextFieldresultado;
    // End of variables declaration//GEN-END:variables
}
